# Generated by Django 3.2 on 2021-04-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='accum_volume',
            field=models.CharField(max_length=255, verbose_name='Объём батареи'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объём памяти'),
        ),
    ]
